python start_date.py --mjd_plus 0
python start_date.py --mjd_plus 1
python start_date.py --mjd_plus 2
python start_date.py --mjd_plus 3
python start_date.py --mjd_plus 4
python start_date.py --mjd_plus 5
python start_date.py --mjd_plus 6
python start_date.py --mjd_plus 7
python start_date.py --mjd_plus 8
python start_date.py --mjd_plus 9
python start_date.py --mjd_plus 10
